language: node_js
node_js:
  - '0.10'
env:
  CODECLIMATE_REPO_TOKEN=1df0094d49925b4e39c410adcb512ddd938a4a8a91c6e7d55c51709f7d8ad8a9
before_script:
  - export PATH="$PATH:$(npm bin)"
script:
  - gulp lint
  - gulp test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate < ./coverage/lcov.info
